default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: urlshortener_development
  username: rails_application
  password: insecure

test:
  <<: *default
  database: urlshortener_test
  username: rails_application
  password: insecure

production:
  <<: *default
  database: urlshortener_production
  username: TBD
  password: TBD
